package com.store.entity;

// Generated Nov 18, 2014 12:29:08 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderRecord generated by hbm2java
 */
@Entity
@Table(name = "order_record", catalog = "mydb")
public class OrderRecord implements java.io.Serializable {

	private int id;
	private User user;
	private PaymentGateway paymentGateway;
	private Product product;
	private Date createtime;
	private Date lastmodifytime;

	public OrderRecord() {
	}

	public OrderRecord(int id, User user, PaymentGateway paymentGateway,
			Product product, Date createtime) {
		this.id = id;
		this.user = user;
		this.paymentGateway = paymentGateway;
		this.product = product;
		this.createtime = createtime;
	}

	public OrderRecord(int id, User user, PaymentGateway paymentGateway,
			Product product, Date createtime, Date lastmodifytime) {
		this.id = id;
		this.user = user;
		this.paymentGateway = paymentGateway;
		this.product = product;
		this.createtime = createtime;
		this.lastmodifytime = lastmodifytime;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_gateway_id", nullable = false)
	public PaymentGateway getPaymentGateway() {
		return this.paymentGateway;
	}

	public void setPaymentGateway(PaymentGateway paymentGateway) {
		this.paymentGateway = paymentGateway;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createtime", nullable = false, length = 19)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifytime", length = 19)
	public Date getLastmodifytime() {
		return this.lastmodifytime;
	}

	public void setLastmodifytime(Date lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

}
