package com.store.entity;

// Generated Nov 18, 2014 12:29:08 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private int id;
	private String productkey;
	private String desc;
	private Date lastmodifytime;
	private Set<OrderRecord> orderRecords = new HashSet<OrderRecord>(0);
	private Set<ShoppingCartHasProduct> shoppingCartHasProducts = new HashSet<ShoppingCartHasProduct>(
			0);
	private Set<SubscriptionStatus> subscriptionStatuses = new HashSet<SubscriptionStatus>(
			0);
	private Set<VpnServer> vpnServers = new HashSet<VpnServer>(
			0);
	
	
	public Product() {
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	

	@Column(name = "productkey", length = 45)
	public String getProductkey() {
		return this.productkey;
	}

	public void setProductkey(String productkey) {
		this.productkey = productkey;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifytime", length = 19)
	public Date getLastmodifytime() {
		return this.lastmodifytime;
	}

	public void setLastmodifytime(Date lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderRecord> getOrderRecords() {
		return this.orderRecords;
	}

	public void setOrderRecords(Set<OrderRecord> orderRecords) {
		this.orderRecords = orderRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ShoppingCartHasProduct> getShoppingCartHasProducts() {
		return this.shoppingCartHasProducts;
	}

	public void setShoppingCartHasProducts(
			Set<ShoppingCartHasProduct> shoppingCartHasProducts) {
		this.shoppingCartHasProducts = shoppingCartHasProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<SubscriptionStatus> getSubscriptionStatuses() {
		return this.subscriptionStatuses;
	}

	public void setSubscriptionStatuses(
			Set<SubscriptionStatus> subscriptionStatuses) {
		this.subscriptionStatuses = subscriptionStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<VpnServer> getVpnServers() {
		return vpnServers;
	}

	public void setVpnServers(Set<VpnServer> vpnServers) {
		this.vpnServers = vpnServers;
	}

}
