package com.store.entity;

// Generated Nov 18, 2014 12:29:08 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private int id;
	private ProductGroup productGroup;
	private String productkey;
	private String desc;
	private Date lastmodifytime;
	private Set<OrderRecord> orderRecords = new HashSet<OrderRecord>(0);
	private Set<ShoppingCartHasProduct> shoppingCartHasProducts = new HashSet<ShoppingCartHasProduct>(
			0);
	private Set<SubscriptionStatus> subscriptionStatuses = new HashSet<SubscriptionStatus>(
			0);

	public Product() {
	}

	public Product(int id, ProductGroup productGroup) {
		this.id = id;
		this.productGroup = productGroup;
	}

	public Product(int id, ProductGroup productGroup, String productkey,
			String desc, Date lastmodifytime, Set<OrderRecord> orderRecords,
			Set<ShoppingCartHasProduct> shoppingCartHasProducts,
			Set<SubscriptionStatus> subscriptionStatuses) {
		this.id = id;
		this.productGroup = productGroup;
		this.productkey = productkey;
		this.desc = desc;
		this.lastmodifytime = lastmodifytime;
		this.orderRecords = orderRecords;
		this.shoppingCartHasProducts = shoppingCartHasProducts;
		this.subscriptionStatuses = subscriptionStatuses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_group_id", nullable = false)
	public ProductGroup getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(ProductGroup productGroup) {
		this.productGroup = productGroup;
	}

	@Column(name = "productkey", length = 45)
	public String getProductkey() {
		return this.productkey;
	}

	public void setProductkey(String productkey) {
		this.productkey = productkey;
	}

	@Column(name = "desc", length = 45)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastmodifytime", length = 19)
	public Date getLastmodifytime() {
		return this.lastmodifytime;
	}

	public void setLastmodifytime(Date lastmodifytime) {
		this.lastmodifytime = lastmodifytime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderRecord> getOrderRecords() {
		return this.orderRecords;
	}

	public void setOrderRecords(Set<OrderRecord> orderRecords) {
		this.orderRecords = orderRecords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ShoppingCartHasProduct> getShoppingCartHasProducts() {
		return this.shoppingCartHasProducts;
	}

	public void setShoppingCartHasProducts(
			Set<ShoppingCartHasProduct> shoppingCartHasProducts) {
		this.shoppingCartHasProducts = shoppingCartHasProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<SubscriptionStatus> getSubscriptionStatuses() {
		return this.subscriptionStatuses;
	}

	public void setSubscriptionStatuses(
			Set<SubscriptionStatus> subscriptionStatuses) {
		this.subscriptionStatuses = subscriptionStatuses;
	}

}
