package com.store.entity;

// Generated Nov 18, 2014 12:29:08 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductGroup generated by hbm2java
 */
@Entity
@Table(name = "product_group", uniqueConstraints = @UniqueConstraint(columnNames = "groupkey"))
public class ProductGroup implements java.io.Serializable {

	private int id;
	private String groupkey;
	private String desc;
	private Set<SubscriptionStatus> subscriptionStatuses = new HashSet<SubscriptionStatus>(
			0);
	private Set<ShoppingCartHasProduct> shoppingCartHasProducts = new HashSet<ShoppingCartHasProduct>(
			0);
	private Set<Product> products = new HashSet<Product>(0);

	public ProductGroup() {
	}

	public ProductGroup(int id, String groupkey) {
		this.id = id;
		this.groupkey = groupkey;
	}

	public ProductGroup(int id, String groupkey, String desc,
			Set<SubscriptionStatus> subscriptionStatuses,
			Set<ShoppingCartHasProduct> shoppingCartHasProducts,
			Set<Product> products) {
		this.id = id;
		this.groupkey = groupkey;
		this.desc = desc;
		this.subscriptionStatuses = subscriptionStatuses;
		this.shoppingCartHasProducts = shoppingCartHasProducts;
		this.products = products;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "groupkey", unique = true, nullable = false, length = 45)
	public String getGroupkey() {
		return this.groupkey;
	}

	public void setGroupkey(String groupkey) {
		this.groupkey = groupkey;
	}

	@Column(name = "desc")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productGroup")
	public Set<SubscriptionStatus> getSubscriptionStatuses() {
		return this.subscriptionStatuses;
	}

	public void setSubscriptionStatuses(
			Set<SubscriptionStatus> subscriptionStatuses) {
		this.subscriptionStatuses = subscriptionStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productGroup")
	public Set<ShoppingCartHasProduct> getShoppingCartHasProducts() {
		return this.shoppingCartHasProducts;
	}

	public void setShoppingCartHasProducts(
			Set<ShoppingCartHasProduct> shoppingCartHasProducts) {
		this.shoppingCartHasProducts = shoppingCartHasProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productGroup")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
